# Generated by Django 6.1.2 on 2026-10-09 03:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(choices=[('PROGRAMMING', 'PROGRAMMING'), ('LANGUAGE', 'LANGUAGE'), ('ACADEMIC', 'ACADEMIC'), ('INTERVIEW', 'INTERVIEW'), ('OTHER', 'OTHER')], default='OTHER', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('hint', models.CharField(blank=True, max_length=200)),
                ('box', models.PositiveSmallIntegerField(default=1)),
                ('next_review_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('times_reviewed', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='study.deck')),
            ],
            options={
                'ordering': ['box', 'next_review_at'],
            },
        ),
    ]
